### ISSUE TITLE
Pi3 UART change

### ISSUE THREAD

**Issue by sourceperl** [SNOC/rpisigfox#1]
Hi,

On the Raspberry Pi 3, /dev/ttyAMA0 is currently used by bluetooth HCI interface.

pi@raspberrypi:~ $ sudo lsof /dev/ttyAMA0 
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
hciattach 614 root    3u   CHR 204,64      0t0 5127 /dev/ttyAMA0

The GPIO UART is now at /dev/ttyS0 for current Raspbian jessie release. But, at this time, the baudrate is wrong and need a manual fix (see http://www.briandorey.com/post/Raspberry-Pi-3-UART-Overlay-Workaround).

**Comment by mroi-snoc** [comment]
Hi,

The ability to use another serial port was added in the python script to allow use of /dev/ttyS0.

Follow the discussion on Raspberry site regarding how to configure the system, as an example at https://www.raspberrypi.org/forums/viewtopic.php?p=927917#p927917
