### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by felice64** [SNOC/rpisigfox#13]
I am on Raspberry Pi 4. I did copy the script but now I am getting this error when running it:

```
pi@raspberrypi:~/WorkInProgress $ ./sendsigfox.py CCDD /dev/tty1
  File "./sendsigfox.py", line 61
    print 'Serial port : ' + portName
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Serial port : ' + portName)?

```
I don't think the error message is correct. However I cannot get the script to run with our errors.
Any hint?

**Comment by ydessert** [comment]
This script is indended to be run with python 2.x.

**Comment by felice64** [comment]
> This script is indended to be run with python 2.x.

Thanks. Is there a Python3 script that I can use?

**Comment by felice64** [comment]
Hi there,
I would appreciate your hint on this.
Any reason why after running the script in Python2 the output it is stuck on "Sending SigFox Message..." and no message is received on the sigfox backend?
Thanks
