### ISSUE TITLE
rpisigfox board  does not work after 

### ISSUE THREAD

**Issue by orivaille** [SNOC/rpisigfox#3]
Hello  
on an all new Raspberry Pi 3    equiped with  a  rpisigfox board and the  Debian cheaped with rhe Pi  (Linux Raspberry 4.1.....) I ran successfully the sendsigfox.py CCDD /dev/ttySO  test script.
After having done a dist updgrade  , I have now Debian 8.0  , Linux raspberry 4.4.9-7+ # 884 
and cannot use the rpisigfox board  anymore : 

pi@raspberrypi:~ $ python sendsigfox.py CCDD /dev/ttyS0
Sending SigFox Message...
Serial port : /dev/ttyS0
Receive timeout ()
SigFox Modem Error

I checked and reinstalled all .py modules  :  python-serial is OK
I checked the "Disable Raspberry Pi terminal on serial port " : OK

The board  is OK 
I set the time-out delay to x3 .. no change

I cannot get back to the previous state before upgrade.
Did  you receive issues  like mine ?

thanks for your help
olivier rivaille

**Comment by mroi-snoc** [comment]
Hello,

The following fixed the issue : 

In '/boot/config.txt' disable if present 'dtoverlay=pi3-miniuart-bt' :
#dtoverlay=pi3-miniuart-bt

Add if necessary :
dtoverlay=pi3-disable-bt
enable_uart=1

Then reboot : 
sudo reboot

Serial port to use is the script's default one : /dev/ttyAMA0

Hope this helps,

Maximilien.

**Comment by luisomoreau** [comment]
Hello,

I'm currently doing a prototype with the SNOC RPISIGFOX and I was wondering where could I find the technical specification. For instance, get the ID and PAC number through AT commands etc...

Thank you!
