### ISSUE TITLE
Technical documentation

### ISSUE THREAD

**Issue by luisomoreau** [SNOC/rpisigfox#4]
Hello,

I'm currently doing a prototype using the RPISIGFOX SNOC shield.
I was wondering how can I get the ID or the PAC number through AT commands.
Is there any technical documentation somewhere? 

Thank you

**Comment by ydessert** [comment]
Hi, 

Board is based on TD1207 chip and user manual is available here:
https://github.com/Telecom-Design/Documentation_TD_RF_Module/raw/master/TD1207%20Reference%20Manual.pdf

To get the ID you can use ATI7 command.

The PAC is not stored in the device as it is a autorization code for the SigFox network and can vary during the life of the device.

Hope it helps.

**Comment by luisomoreau** [comment]
Great!!
Thanks a lot for your fast anwser!
