### ISSUE TITLE
Receive timeout, Modem Error

### ISSUE THREAD

**Issue by schtipoun** [SNOC/rpisigfox#5]
Bonjour, 

J'ai acheté une [carte](http://yadom.fr/carte-de-communication-sigfox.html) sur le site de Yadom avec le cable et l'antenne. 
Je l'ai banché sur ma Raspberry Pi 2 Model B V1.1 qui tourne sous Linux raspberry 4.4.11 (le U1 de la carte sur le GPIO1, 3V3 sur la Raspberry).
J'ai désactivé le serial port comme indiqué mais malgré tout j'obtiens un message d'erreur.

```
pi@raspberrypi:~ $ python sendsigfox.py CCDD /dev/ttyS0
Sending SigFox Message...
Serial port : /dev/ttyS0
Receive timeout ()
SigFox Modem Error
```

Ensuite, ce qui est perturbant, c'est qu'il n'y a pas de LED sur la carte donc je ne sais même pas si électriquement elle est bien branchée. J'ai demandé au constructeur et il m'a confirmé qu'il n'y avait pas de LED.

Merci d'avance pour votre aide.
^antoine

**Comment by mroi-snoc** [comment]
Bonjour,

Ces scripts ne sont pas prévus pour fonctionner avec la carte que vous utilisez.

Veuillez prendre contact avec le support Yadom : support_at_yadom.fr

Merci,

Maximilien.
