### ISSUE TITLE
No error when network out of range

### ISSUE THREAD

**Issue by bjsi9** [SNOC/rpisigfox#7]
Hi, i'm enjoying these script big time.

But there seems to be an error running this script out of network coverage. Meaning: when i run this script from where there is no sigfox network coverage, and i confirm that my sigfox backend dosent get the message. The script is still given me "message sent" and "answer received".

Script: sendreceivesigfox.py

**Comment by mroi-snoc** [comment]
Hi, we are glad you enjoy using these scripts.

About the use without coverage :
- the module just sends the message without "knowing" if there is a listening device - for low power reasons. That makes it displaying the message is sent as there was no error it could detect when sending it.
- regarding the receiving acknowledgement, could you please try the AT sequence directly with the TD1207 chip ? Minicom or alike software should do the trick. You can as well add one line with print rxData after line 113. There might be data one should detect to point out there was no answer.

Happy SigFoxing !

**Comment by bjsi9** [comment]
Hi, thank you for quick support.  

The "print rxData" looks like the right way for me. 

But it still give me "+RX END" same if in coverage or without coverage. See picture, I have added the print rxData after line 113. And sent message from without coverage, and confirm that no message is received in sigfox backend.
![billede 26-10-2016 09 43 21](https://cloud.githubusercontent.com/assets/23030614/19717423/d64c1c78-9b60-11e6-8d3a-f2e683b44a50.jpg)

If i do the same thing inside network coverage i get the exact same command outputs. But the message is received in Sigfox backend, and acked. Furthermore i can from the sigfox backend find hexa data that confirms the ACK. see picture from sigfox backend
<img width="616" alt="skaermbillede 2016-10-26 kl 09 55 15" src="https://cloud.githubusercontent.com/assets/23030614/19717735/531c2c42-9b62-11e6-909c-e89feb86f0b1.png">

I have researched other similar scripts (written to other devices on other language codes). They have a code line about downlink rx_frame. So the script get ACK data from sigfox backend. This data could be used to determine if there was an ACK or no. Heres the link and picture for reference:
<img width="740" alt="skaermbillede 2016-10-26 kl 09 57 38" src="https://cloud.githubusercontent.com/assets/23030614/19717851/dcff973c-9b62-11e6-87cd-e911b485106f.png">

This kind of feature could give the final touch to a reliable product. I hope we can work together for a solution.

Kind regards

**Comment by bjsi9** [comment]
This small forum thread explains exactly the challenge. And it's using the AT commands for retrieving the data from the downlink. 
This would be great to implement
https://www.cooking-hacks.com/forum/viewtopic.php?f=37&t=8280

**Comment by bjsi9** [comment]
i got it :) replaced 'END' with '+RX=' in the receiving part of the script. Now the script stops and fails if there is no answer. 
Thanks for hints 👍

**Comment by mroi-snoc** [comment]
Well done ! We will merge your changes to enhance this script.

Thanks a lot for sharing problems and solutions.

Maximilien.
