### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by bjsi9** [SNOC/rpisigfox#8]
Hi,

I'm sorry, but i didn't know were else to ask this question. I get no answer on snoc.fr homepage email form.

It's a simpe question: Does the snoc rpisigfox module come with pre condigured firmware settings? Meaning if i do AT commands like "ATZ" and "AT&F" that restore to factory default, would that destroy the option to communicate with sigfox?

**Comment by ydessert** [comment]
Hi,
The SigFox information are stored during manufacturing in the module.
So it's safe to use AT&F to restore factory default, no risk to loose any access.

Have fun with the RPISIFOX module !

Yannick

**Comment by bjsi9** [comment]
Thank you for quick support and good answer. Just to be 100% sure, the "ATZ" command is also safe to use? 
ATZ command:
"_This command restores the configuration profile from non-volatile memory (Flash).
Note: As a Telecom Design extension, this command also resets the module to its power-on state._"

**Comment by ydessert** [comment]
Yes it's safe, no problem to use ATZ.
