### ISSUE TITLE
Board not working?

### ISSUE THREAD

**Issue by bjsi9** [SNOC/rpisigfox#9]
Hi,
Suddenly from one day to another i couldnt send message over sigfox network. I have tested and tested since last month, and i'm  desperate to get som eyes on my issue.
I have made a detailed documentation, describing issue and the troubleshooting i have made. 

Could you point me in the right direction? See attached pdf:
[Error and testing.pdf](https://github.com/SNOC/rpisigfox/files/587806/Error.and.testing.pdf)

**Comment by mroi-snoc** [comment]
Hi,

For hardware issues, please use the dedicated channel : service-client@yadom.fr

Gihub is preferably used for software issues.

We look forward receiving your message shortly.

The SNOC team.
